# Generated by Django 5.2.4 on 2025-08-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stud_id", models.CharField(max_length=50)),
                ("bus_id", models.IntegerField()),
                ("description", models.TextField()),
                ("time", models.DateField(auto_now=True)),
                ("teacher_id", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("teacher_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(blank=True, max_length=50)),
                ("class_no", models.IntegerField()),
                ("branch", models.CharField(max_length=50)),
                ("sem", models.CharField(max_length=50)),
            ],
        ),
    ]
