# Generated by Django 5.2.4 on 2025-09-06 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0002_missingstudentalert_missingstudentreport_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MissingStudentReport",
        ),
    ]
