# Generated by Django 5.2.4 on 2025-09-06 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0003_delete_missingstudentreport"),
    ]

    operations = [
        migrations.DeleteModel(
            name="report",
        ),
    ]
