# Generated by Django 5.2.4 on 2025-09-12 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0005_passwordresettoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="password",
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
