# Generated by Django 5.2.4 on 2025-09-12 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0006_alter_teacher_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="missingstudentalert",
            name="parent_contact",
            field=models.CharField(max_length=100),
        ),
    ]
