# Generated by Django 5.2.4 on 2025-09-16 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0007_alter_missingstudentalert_parent_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="class_no",
            field=models.CharField(max_length=10),
        ),
    ]
