# Generated by Django 5.2.4 on 2025-09-06 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0002_passwordresettoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="management",
            name="password",
            field=models.CharField(max_length=128),
        ),
    ]
