# Generated by Django 5.2.6 on 2025-09-21 16:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bus_no", models.IntegerField()),
                ("bus_starting_point", models.CharField(max_length=50)),
                ("bus_plate", models.CharField(max_length=50)),
                ("bus_photo", models.ImageField(blank=True, upload_to="bus")),
                ("departure_time", models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Busdriver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bus_driver", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(blank=True, max_length=128)),
                ("ph_no", models.CharField(max_length=50)),
                ("status", models.CharField(default="permanent", max_length=50)),
                ("bus_photo", models.ImageField(blank=True, upload_to="change bus")),
                (
                    "bus_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="driver.bus"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BusMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=100)),
                ("message", models.TextField()),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("all_parents", "All Parents"),
                            ("school_admin", "School Admin"),
                            ("specific_parent", "Specific Parent"),
                        ],
                        max_length=20,
                    ),
                ),
                ("parent_contact", models.CharField(blank=True, max_length=100)),
                ("sent_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="driver.busdriver",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentBoarding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("time", models.TimeField(blank=True, null=True)),
                ("morning_scan", models.BooleanField(default=False)),
                (
                    "morning_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "morning_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("evening_scan", models.BooleanField(default=False)),
                (
                    "evening_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "evening_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("boarded", "Boarded"),
                            ("not_boarded", "Not Boarded"),
                            ("departed", "Departed"),
                        ],
                        default="not_boarded",
                        max_length=20,
                    ),
                ),
                ("alert_sent", models.BooleanField(default=False)),
                (
                    "bus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="driver.bus"
                    ),
                ),
            ],
        ),
    ]
