# Generated by Django 5.2.4 on 2025-08-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bus_no", models.IntegerField()),
                ("bus_starting_point", models.CharField(max_length=50)),
                ("bus_stoping_point", models.CharField(max_length=50)),
                ("bus_plate", models.CharField(max_length=50)),
                ("bus_change", models.CharField(max_length=50)),
            ],
        ),
    ]
