# Generated by Django 5.2.4 on 2025-08-17 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bus_no", models.IntegerField()),
                ("bus_starting_point", models.CharField(max_length=50)),
                ("bus_plate", models.CharField(max_length=50)),
                ("bus_photo", models.ImageField(blank=True, upload_to="bus")),
            ],
        ),
        migrations.CreateModel(
            name="Busdriver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bus_driver", models.CharField(max_length=50)),
                ("ph_no", models.CharField(max_length=50)),
                ("status", models.CharField(default="permanent", max_length=50)),
                ("bus_photo", models.ImageField(blank=True, upload_to="change bus")),
                (
                    "bus_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="driver.bus"
                    ),
                ),
            ],
        ),
    ]
