# Generated by Django 5.2.6 on 2025-09-21 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("driver", "0001_initial"),
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentboarding",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="student.student_details",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="studentboarding",
            unique_together={("student", "bus", "date")},
        ),
    ]
