# Generated by Django 5.2.4 on 2025-08-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("driver", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bus",
            name="driver_name",
            field=models.CharField(default="1", max_length=50),
            preserve_default=False,
        ),
    ]
