# Generated by Django 5.2.4 on 2025-08-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("driver", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="busdriver",
            name="email",
            field=models.EmailField(default="1", max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="busdriver",
            name="password",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
