# Generated by Django 5.2.4 on 2025-09-07 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("driver", "0002_busdriver_email_busdriver_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="busdriver",
            name="last_updated",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="busdriver",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="busdriver",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
    ]
