# Generated by Django 5.2.4 on 2025-09-10 15:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("driver", "0003_busdriver_last_updated_busdriver_latitude_and_more"),
        ("student", "0007_alter_student_details_password"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="busdriver",
            name="last_updated",
        ),
        migrations.RemoveField(
            model_name="busdriver",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="busdriver",
            name="longitude",
        ),
        migrations.AddField(
            model_name="bus",
            name="departure_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="BoardingAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("boarded", "Boarded"),
                            ("not_boarded", "Not Boarded"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "sent_to",
                    models.CharField(
                        choices=[("teacher", "Teacher"), ("driver", "Driver")],
                        max_length=20,
                    ),
                ),
                ("sent_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "bus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="driver.bus"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student.student_details",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BusMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=100)),
                ("message", models.TextField()),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("all_parents", "All Parents"),
                            ("school_admin", "School Admin"),
                            ("specific_parent", "Specific Parent"),
                        ],
                        max_length=20,
                    ),
                ),
                ("parent_contact", models.CharField(blank=True, max_length=100)),
                ("sent_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="driver.busdriver",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentBoarding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("time", models.TimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("boarded", "Boarded"),
                            ("not_boarded", "Not Boarded"),
                            ("departed", "Departed"),
                        ],
                        default="not_boarded",
                        max_length=20,
                    ),
                ),
                ("alert_sent", models.BooleanField(default=False)),
                (
                    "bus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="driver.bus"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student.student_details",
                    ),
                ),
            ],
        ),
    ]
