# Generated by Django 5.2.4 on 2025-09-11 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("driver", "0004_remove_busdriver_last_updated_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="busdriver",
            name="password",
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
