# Generated by Django 5.2.4 on 2025-09-11 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("driver", "0005_alter_busdriver_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="busdriver",
            name="bus_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="driver.bus",
                unique=True,
            ),
        ),
    ]
