# Generated by Django 5.2.4 on 2025-09-11 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("driver", "0006_alter_busdriver_bus_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boardingalert",
            name="alert_type",
            field=models.CharField(
                choices=[
                    ("boarded", "Boarded"),
                    ("not_boarded", "Not Boarded"),
                    ("unregistered", "Unregistered"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="busdriver",
            name="bus_id",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="driver.bus"
            ),
        ),
    ]
