# Generated by Django 5.2.4 on 2025-09-14 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("driver", "0007_alter_boardingalert_alert_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentboarding",
            name="time",
        ),
        migrations.AddField(
            model_name="boardingalert",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="boardingalert",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="studentboarding",
            name="evening_latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="studentboarding",
            name="evening_longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="studentboarding",
            name="evening_scan",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="studentboarding",
            name="morning_latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="studentboarding",
            name="morning_longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="studentboarding",
            name="morning_scan",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="boardingalert",
            name="alert_type",
            field=models.CharField(
                choices=[
                    ("boarded", "Boarded"),
                    ("not_boarded", "Not Boarded"),
                    ("unregistered", "Unregistered"),
                    ("not_boarded_morning", "Not Boarded Morning"),
                    ("not_boarded_evening", "Not Boarded Evening"),
                ],
                max_length=30,
            ),
        ),
    ]
