# Generated by Django 5.2.4 on 2025-09-14 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("driver", "0008_remove_studentboarding_time_boardingalert_latitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentboarding",
            name="time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
