# Generated by Django 5.2.6 on 2025-09-21 16:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("driver", "0001_initial"),
        ("parent", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="student_complaints",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_id", models.IntegerField()),
                ("complaint", models.TextField()),
                ("bus", models.CharField(max_length=50)),
                (
                    "complaint_by",
                    models.CharField(blank=True, default="Student", max_length=10),
                ),
                ("date", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(blank=True, max_length=50)),
                ("action_taken", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="student_details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=128)),
                ("phone_no", models.CharField(max_length=10)),
                ("stud_class", models.CharField(max_length=50)),
                ("branch", models.CharField(max_length=50)),
                (
                    "accommodation_type",
                    models.CharField(default="Day Scholar", max_length=50),
                ),
                ("is_boarded", models.BooleanField(default=False)),
                ("boarding_time", models.DateTimeField(blank=True, null=True)),
                (
                    "bus",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="driver.bus",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="parent.parent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="registery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("FN", models.CharField(max_length=20)),
                ("AN", models.CharField(max_length=20)),
                (
                    "student_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student.student_details",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PasswordResetToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student.student_details",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="hosteler_reg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pickup_time", models.CharField(max_length=50)),
                ("pickup_point", models.CharField(max_length=50)),
                ("status", models.CharField(blank=True, max_length=50)),
                ("time", models.DateTimeField(auto_now=True)),
                (
                    "bus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="driver.bus"
                    ),
                ),
                (
                    "student_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student.student_details",
                    ),
                ),
            ],
        ),
    ]
