# Generated by Django 5.2.4 on 2025-08-14 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="hosteler_reg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_id", models.IntegerField()),
                ("pickup_time", models.CharField(max_length=50)),
                ("pickup_point", models.CharField(max_length=50)),
                ("bus_id", models.IntegerField()),
                ("status", models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="registery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("FN", models.CharField(max_length=20)),
                ("AN", models.CharField(max_length=20)),
                ("student_id", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="student_complaints",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_id", models.IntegerField()),
                ("complaint", models.TextField()),
                ("bus", models.IntegerField()),
                (
                    "complaint_by",
                    models.CharField(blank=True, default="Student", max_length=10),
                ),
                ("date", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(blank=True, max_length=50)),
                ("action_taken", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="student_details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(blank=True, max_length=70)),
                ("phone_no", models.CharField(max_length=10)),
                ("stud_class", models.CharField(max_length=50)),
                ("branch", models.CharField(max_length=50)),
                (
                    "accommodation_type",
                    models.CharField(default="Day Scholar", max_length=50),
                ),
                ("bus", models.IntegerField()),
            ],
        ),
    ]
