# Generated by Django 5.2.4 on 2025-08-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="student_details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=70)),
                ("phone_no", models.IntegerField(max_length=10)),
                ("parent_ph_no", models.IntegerField(max_length=10)),
            ],
        ),
    ]
