# Generated by Django 5.2.4 on 2025-08-25 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("driver", "0002_busdriver_email_busdriver_password"),
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hosteler_reg",
            name="student",
        ),
        migrations.AddField(
            model_name="hosteler_reg",
            name="student_id",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="student.student_details",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="hosteler_reg",
            name="bus",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="driver.bus"
            ),
        ),
    ]
