# Generated by Django 5.2.4 on 2025-08-09 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0002_alter_student_details_parent_ph_no_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student_details",
            name="parent_ph_no",
        ),
    ]
