# Generated by Django 5.2.4 on 2025-08-25 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "student",
            "0002_remove_hosteler_reg_student_hosteler_reg_student_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="hosteler_reg",
            name="student_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="student.student_details",
            ),
        ),
    ]
