# Generated by Django 5.2.4 on 2025-09-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0003_alter_hosteler_reg_student_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student_details",
            name="password",
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
