# Generated by Django 5.2.4 on 2025-08-09 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0003_remove_student_details_parent_ph_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="student_details",
            name="key",
            field=models.CharField(default="WXYZ", max_length=100),
            preserve_default=False,
        ),
    ]
