# Generated by Django 5.2.4 on 2025-08-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0004_student_details_key"),
    ]

    operations = [
        migrations.CreateModel(
            name="registery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("FN", models.CharField(max_length=20)),
                ("AN", models.CharField(max_length=20)),
                ("student_id", models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name="student_details",
            name="branch",
            field=models.CharField(default="1", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="student_details",
            name="stud_class",
            field=models.CharField(default="x", max_length=50),
            preserve_default=False,
        ),
    ]
