# Generated by Django 5.2.4 on 2025-09-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0004_alter_student_details_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student_details",
            name="password",
            field=models.CharField(default="", max_length=70),
            preserve_default=False,
        ),
    ]
