# Generated by Django 5.2.4 on 2025-08-10 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0005_registery_student_details_branch_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student_details",
            name="password",
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
