# Generated by Django 5.2.4 on 2025-09-06 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0006_passwordresettoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student_details",
            name="password",
            field=models.CharField(max_length=128),
        ),
    ]
