# Generated by Django 5.2.4 on 2025-08-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0006_alter_student_details_password"),
    ]

    operations = [
        migrations.CreateModel(
            name="hosteler_reg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_name", models.CharField(max_length=50)),
                ("pickup_point", models.CharField(max_length=50)),
                ("bus_id", models.CharField(max_length=50)),
                ("status", models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="student_complaints",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_id", models.IntegerField()),
                ("complaint", models.TextField()),
                ("date", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(blank=True, max_length=50)),
                ("action_taken", models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name="student_details",
            name="accommodation_type",
            field=models.CharField(default="Day Scholar", max_length=50),
            preserve_default=False,
        ),
    ]
