# Generated by Django 5.2.4 on 2025-08-10 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0007_hosteler_reg_student_complaints_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student_details",
            name="key",
        ),
    ]
