# Generated by Django 5.2.4 on 2025-09-11 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parent", "0002_complaint"),
        ("student", "0007_alter_student_details_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="student_details",
            name="boarding_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student_details",
            name="is_boarded",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="student_details",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="parent.parent",
            ),
        ),
    ]
