# Generated by Django 5.2.4 on 2025-08-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0008_remove_student_details_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student_details",
            name="accommodation_type",
            field=models.CharField(default="Day Scholar", max_length=50),
        ),
    ]
