# Generated by Django 5.2.4 on 2025-08-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0009_alter_student_details_accommodation_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student_details",
            name="phone_no",
            field=models.CharField(max_length=10),
        ),
    ]
