# Generated by Django 5.2.4 on 2025-08-12 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0010_alter_student_details_phone_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="student_complaints",
            name="bus",
            field=models.CharField(default="y", max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="student_complaints",
            name="complaint_by",
            field=models.CharField(blank=True, default="Student", max_length=10),
        ),
    ]
