# Generated by Django 5.2.4 on 2025-08-13 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0011_student_complaints_bus_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student_complaints",
            name="bus",
            field=models.IntegerField(),
        ),
    ]
