# Generated by Django 5.2.4 on 2025-08-14 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0012_alter_student_complaints_bus"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hosteler_reg",
            old_name="student_name",
            new_name="pickup_time",
        ),
        migrations.AddField(
            model_name="hosteler_reg",
            name="student_id",
            field=models.IntegerField(default="y"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="hosteler_reg",
            name="bus_id",
            field=models.IntegerField(),
        ),
    ]
